[package]
name = "project2-service"
version = "0.1.0"
edition = "2024"

[dependencies]
shared-types = { nexus = true }
shared-utils = { nexus = true }
tokio = { version = "1.0", features = ["full"] }
log = "0.4"